TOKEN=ETCD_TOKEN
THIS_HOSTNAME=$1
THIS_IP=$2
HOSTNAME_1=$3
IP_1=$4
HOSTNAME_2=$5
IP_2=$6
cat << EOF > /etc/default/etcd
ETCD_NAME="$THIS_HOSTNAME"
ETCD_LISTEN_PEER_URLS="http://$THIS_IP:2380"
ETCD_LISTEN_CLIENT_URLS="http://$THIS_IP:2379,http://127.0.0.1:2379"
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://$THIS_IP:2380"
ETCD_ADVERTISE_CLIENT_URLS="http://$THIS_IP:2379"
ETCD_INITIAL_CLUSTER="$THIS_HOSTNAME=http://$THIS_IP:2380,$HOSTNAME_1=http://$IP_1:2380,$HOSTNAME_2=http://$IP_2:2380"
ETCD_INITIAL_CLUSTER_TOKEN="$TOKEN"
ETCD_INITIAL_CLUSTER_STATE="new"
EOF
